site_name: "M3 Annosaurus"
theme:
    name: 'material'
    logo: https://docs.mbari.org/imgs/mbari-logo.png
extra_css:
    - https://docs.mbari.org/css/mbari.css
    - assets/css/extra.css

plugins:
  - search
  - mermaid2:
      version: 9.1.4

markdown_extensions:
  - footnotes
  - toc:
      permalink: True

nav:
  - Home: index.md
  - 'How-to':
    - 'Security Handshake': howto/security_handshake.md
    - 'Fetch Annotations': howto/fetch_annotations.md
  - About:
    - 'GitHub': "https://github.com/mbari-media-management/annosaurus"
  - MBARI Docs: "https://docs.mbari.org"
